USE [master]
GO

/****** Object:  Database [Insight]    Script Date: 8/21/2014 10:55:17 PM ******/
CREATE DATABASE [Insight]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Insight', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Insight.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Insight_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\Insight_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Insight] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Insight].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Insight] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Insight] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Insight] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Insight] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Insight] SET ARITHABORT OFF 
GO

ALTER DATABASE [Insight] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Insight] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Insight] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Insight] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Insight] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Insight] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Insight] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Insight] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Insight] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Insight] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Insight] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Insight] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Insight] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Insight] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Insight] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Insight] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Insight] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Insight] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Insight] SET  MULTI_USER 
GO

ALTER DATABASE [Insight] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Insight] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Insight] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Insight] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Insight] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Insight] SET  READ_WRITE 
GO


